### ISSUE TITLE
Example in README dosen't work

### ISSUE THREAD

**Issue by MalikMlitat** [eldaduzman/robotframework-gevent#50]
due to a missing space (should be 2 spaces) after alias1, example not working:
```robotframework
    Create Gevent Bundle    alias=alias1  # Create a bundle of coroutines
```

**Comment by eldaduzman** [comment]
Hi @MalikMlitat and thanks a lot for your contribution, this is a legit bug and it will be merged shortly.

**Comment by eldaduzman** [comment]
Merged, thanks!
